__all__ = [
    "buiksloterkerk",
    "concertgebouw",
    "concertgemaal",
    "cva",
    # "embassy", getting event time is absolutely impossible.
    "erc",
    "gamalanhuis",
    "geelvinck",
    # "grachtenfestival2025",
    "joodsmuseum",
    "kamukoza",
    "keizersgrachtkerk",
    "luthermuseum",
    "muziekgebouw",
    "nieuwekerk",
    "nedpho",
    "orgelpark",
    "rozengracht55",
    "rooderemise",
    "singelkerk",
    "sloterkerk",
    "splendor",
    "stadsherstel",
    "stopera",
    "studio150",
    "thomas",
    "uilenburgersjoel",
    "waalsekerk",
]
from . import *